/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Complaint {
  'id' : bigint,
  'subject' : string,
  'name' : string,
  'message' : string,
  'timestamp' : Time,
  'image' : [] | [ExternalBlob],
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface LicenseApplication {
  'id' : bigint,
  'dob' : string,
  'licenceType' : string,
  'fullName' : string,
  'email' : string,
  'district' : string,
  'state' : string,
  'address' : string,
  'timestamp' : Time,
  'mobile' : string,
  'photo' : [] | [ExternalBlob],
  'status' : string,
  'paymentScreenshot' : [] | [ExternalBlob],
}
export interface PageView {
  'sessionId' : string,
  'page' : string,
  'timestamp' : Time,
}
export interface TrafficStats {
  'onlineNow' : bigint,
  'totalPageViews' : bigint,
  'recentViews' : Array<PageView>,
}
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'getAssociationInfo' : ActorMethod<[], string>,
  'getComplaints' : ActorMethod<[], Array<Complaint>>,
  'getFaqs' : ActorMethod<[], Array<string>>,
  'getLicenseApplications' : ActorMethod<[], Array<LicenseApplication>>,
  'getMembershipFormUrl' : ActorMethod<[], string>,
  'getServices' : ActorMethod<[], Array<string>>,
  'submitComplaint' : ActorMethod<
    [string, string, string, string, [] | [ExternalBlob]],
    bigint
  >,
  'submitLicenseApplication' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      [] | [ExternalBlob],
      [] | [ExternalBlob],
    ],
    bigint
  >,
  'updateLicenseApplicationStatus' : ActorMethod<[bigint, string], boolean>,
  'recordPageView' : ActorMethod<[string, string], undefined>,
  'sendHeartbeat' : ActorMethod<[string], undefined>,
  'getTrafficStats' : ActorMethod<[], TrafficStats>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
