/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Complaint = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'image' : IDL.Opt(ExternalBlob),
  'phone' : IDL.Text,
});
export const LicenseApplication = IDL.Record({
  'id' : IDL.Nat,
  'dob' : IDL.Text,
  'licenceType' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'district' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : Time,
  'mobile' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'status' : IDL.Text,
  'paymentScreenshot' : IDL.Opt(ExternalBlob),
});

export const PageView = IDL.Record({
  'sessionId' : IDL.Text,
  'page' : IDL.Text,
  'timestamp' : Time,
});

export const TrafficStats = IDL.Record({
  'onlineNow' : IDL.Nat,
  'totalPageViews' : IDL.Nat,
  'recentViews' : IDL.Vec(PageView),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getAssociationInfo' : IDL.Func([], [IDL.Text], ['query']),
  'getComplaints' : IDL.Func([], [IDL.Vec(Complaint)], []),
  'getFaqs' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getLicenseApplications' : IDL.Func([], [IDL.Vec(LicenseApplication)], []),
  'getMembershipFormUrl' : IDL.Func([], [IDL.Text], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'submitComplaint' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'submitLicenseApplication' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
      ],
      [IDL.Nat],
      [],
    ),
  'updateLicenseApplicationStatus' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'recordPageView' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'sendHeartbeat' : IDL.Func([IDL.Text], [], []),
  'getTrafficStats' : IDL.Func([], [TrafficStats], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Complaint = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'image' : IDL.Opt(ExternalBlob),
    'phone' : IDL.Text,
  });
  const LicenseApplication = IDL.Record({
    'id' : IDL.Nat,
    'dob' : IDL.Text,
    'licenceType' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'district' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : Time,
    'mobile' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'status' : IDL.Text,
    'paymentScreenshot' : IDL.Opt(ExternalBlob),
  });
  const PageView = IDL.Record({
    'sessionId' : IDL.Text,
    'page' : IDL.Text,
    'timestamp' : Time,
  });
  const TrafficStats = IDL.Record({
    'onlineNow' : IDL.Nat,
    'totalPageViews' : IDL.Nat,
    'recentViews' : IDL.Vec(PageView),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getAssociationInfo' : IDL.Func([], [IDL.Text], ['query']),
    'getComplaints' : IDL.Func([], [IDL.Vec(Complaint)], []),
    'getFaqs' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getLicenseApplications' : IDL.Func([], [IDL.Vec(LicenseApplication)], []),
    'getMembershipFormUrl' : IDL.Func([], [IDL.Text], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'submitComplaint' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'submitLicenseApplication' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Nat],
        [],
      ),
    'updateLicenseApplicationStatus' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'recordPageView' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'sendHeartbeat' : IDL.Func([IDL.Text], [], []),
    'getTrafficStats' : IDL.Func([], [TrafficStats], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
